### ISSUE TITLE
Cleaning Google Search URLs

### ISSUE THREAD

**Issue by Zero3K** [luciph0r/pureurl4pm#1]
How do I do that with this add-on?

**Comment by luciph0r** [comment]
Go to the addon preferences, and in the textbox marked 'Garbage fields list', add the ones you want to have removed from Google search. If you want the parameter to only be removed from google.com URLs, add it in the form parameter@google.com, else it will be removed from every URL that has it.

**Comment by Zero3K** [comment]
Will it keep the URLs that is in the search results?

**Comment by luciph0r** [comment]
Why don't you try it out, and use the configuration to set the parameters you want to filter. I am not the original author, I have just ported it to Palemoon. This extension isn't magic, you have to configure it to do what you want. Google's parameters are especially hard to get around. Or you could ditch Google altogether if you're that concerned, it's not as though there aren't alternatives.
