### ISSUE TITLE
Embedded YouTube video blocked

### ISSUE THREAD

**Issue by Gittyperson** [luciph0r/pureurl4pm#2]
Go to [this website](https://pitsirikos.net/2019/08/%CE%B4%CE%B5%CE%BD-%CE%BE%CE%AD%CF%81%CF%89-%CE%B1%CE%BD-%CE%B4%CE%BF%CF%85%CE%BB%CE%B5%CF%8D%CE%B5%CE%B9-%CE%BF-%CE%BB%CE%B1%CF%8C%CF%82-%CF%84%CE%B7%CE%BD-%CE%BA%CF%85%CE%B2%CE%AD%CF%81%CE%BD%CE%B7/) and scroll a bit down for the YouTube video. It will not play with Pure URL 1.1.0 enabled.

Not sure what I can do to locate/isolate the issue. Disabling Pure URL makes it work again.

Pale Moon 28.7.0, Pure URL 1.1.0, W10

**Comment by luciph0r** [comment]
Do a 'view source' for the page with and without pure url enabled, see if the YouTube link in the embedded code is different. Pure url maybe removing a parameter that's required. Remove the parameter from its settings and it should work.

**Comment by Gittyperson** [comment]
Thanks, I did that but there are no differences at all in the Page Source output. Also compared them after starting YT playback.

**Comment by luciph0r** [comment]
Okay. Can you share the link where you tried it out?

**Comment by Gittyperson** [comment]
Link is in the first post.

**Comment by luciph0r** [comment]
ok, I'll take a look.

**Comment by luciph0r** [comment]
It's a long shot, but can you see if the problem persists with the original Firefox version of this addon, from the classic addons archive]caa:addon/pure-url/versions)? Version 1.2.4 is what works with PM. 
I have simply changed the application ID and retargeted it for PM, with a few additional default filters.

**Comment by luciph0r** [comment]
You would have to disable this one before installing the other one.

**Comment by luciph0r** [comment]
Ok, scratch that, it works if you remove the filter 'c' from the list. Will remove it from the default list.
