### ISSUE TITLE
Required arguments being removed from e-mail confirmation link on my.fsf.org

### ISSUE THREAD

**Issue by noskla** [luciph0r/pureurl4pm#3]
Go to [this webpage](https://www.fsf.org/free-software-supporter/), sign up for the newsletter on the right, go to the confirm url in received e-mail, error will show up because argument "cid" is being removed.
Disabling Pure URL for Pale Moon makes it work.
Pale Moon 28.7.1, Pure URL 1.2.1, GNU/Linux

**Comment by luciph0r** [comment]
Preferences are editable for a reason. Remove cid from the list of garbage fields in the extension preferences and it's done.
